import type { GameId } from "./content/types";

export type Mood = "talk" | "laugh" | "challenge" | "activity";
/** Catalogue sections (ideas doc §1): talk G01–G08, laugh G09–G16, think G17–G24, outings G25–G30, useful G31–G34, faith G35–G36. */
export type Category = "talk" | "laugh" | "think" | "outings" | "useful" | "faith";

export interface GameMeta {
  id: GameId;
  slug: string;
  name: string; // Arabic
  tagline: string; // one line, Arabic
  why: string; // why play, 1–2 sentences
  steps: [string, string, string]; // instructions in 3 short steps
  minutes: number; // typical session length
  rounds: readonly number[]; // selectable round counts; [] = fixed/n.a.
  fixedRounds?: number; // G04 = 10, G09 = 5, G25 = 1
  depth: "light" | "deep" | "mixed";
  moods: Mood[];
  requiresTools: boolean; // any card may require tools
  requiresMovement: boolean; // any card may require movement
  devices: 1;
  hue: string; // per-game accent (CSS color) — identity, used on cards/chips
  category: Category;
  /** Hidden from every list until the matching setting is switched on (G35). */
  gated?: "religious";
}

export const GAMES: readonly GameMeta[] = [
  {
    id: "G01",
    slug: "conversation-starters",
    name: "فاتحة حديث",
    tagline: "أسئلة قصيرة تفتح كلاماً طويلاً",
    why: "لأن أجمل الأحاديث تبدأ بسؤال بسيط. كل بطاقة سؤال، وكل جواب يُقال بصوتكما لا بأصابعكما.",
    steps: [
      "اختارا الباقة وعدد البطاقات",
      "اقرأ السؤال بصوت عالٍ وأجب",
      "مرّر الهاتف؛ الدور على شريكك",
    ],
    minutes: 10,
    rounds: [5, 10],
    depth: "mixed",
    moods: ["talk"],
    requiresTools: false,
    requiresMovement: false,
    devices: 1,
    hue: "#7A5AF8",
    category: "talk",
  },
  {
    id: "G02",
    slug: "would-you-rather",
    name: "أيّهما تختار؟",
    tagline: "خياران فقط، وتوقّع اختيار شريكك",
    why: "لعبة سريعة تكشف كم تتشابهان في الصغائر، وتضحككما حين تختلفان.",
    steps: ["اختر أحد الخيارَين وثبّت", "مرّر الهاتف ليختار شريكك", "شاهدا اختياريكما معاً"],
    minutes: 8,
    rounds: [5, 10],
    depth: "light",
    moods: ["laugh", "talk"],
    requiresTools: false,
    requiresMovement: false,
    devices: 1,
    hue: "#F0A23B",
    category: "talk",
  },
  {
    id: "G03",
    slug: "which-one-of-us",
    name: "مَن منّا؟",
    tagline: "أنت؟ أنا؟ أم كلانا؟",
    why: "مواقف يومية صغيرة تُظهر كيف يرى كلٌّ منكما الآخر، بلا أحكام.",
    steps: [
      "اقرأ العبارة واختر: أنت، شريكك، أو كلاكما",
      "مرّر الهاتف ليختار شريكك",
      "قارنا الإجابتين",
    ],
    minutes: 8,
    rounds: [5, 10],
    depth: "light",
    moods: ["laugh"],
    requiresTools: false,
    requiresMovement: false,
    devices: 1,
    hue: "#D9647A",
    category: "talk",
  },
  {
    id: "G04",
    slug: "how-well-do-you-know-me",
    name: "كم تعرفني؟",
    tagline: "أحدكما يجيب، والآخر يتوقّع",
    why: "عشر جولات، خمس لكلٍّ منكما. نقطة لكل توقّع صحيح، ولا أحكام على من يخطئ.",
    steps: [
      "يجيب أحدكما عن نفسه سراً",
      "مرّر الهاتف ليتوقّع الآخر",
      "نقطة للتوقّع الصحيح، ثم تبادلا الأدوار",
    ],
    minutes: 12,
    rounds: [],
    fixedRounds: 10,
    depth: "light",
    moods: ["challenge", "talk"],
    requiresTools: false,
    requiresMovement: false,
    devices: 1,
    hue: "#2F9E8F",
    category: "talk",
  },
  {
    id: "G09",
    slug: "one-minute-challenges",
    name: "تحدّي الدقيقة",
    tagline: "خمس مهمات صغيرة، معاً ضد الساعة",
    why: "تحديات تعاونية خفيفة: تمثيل، كلام، حركة بسيطة. تنجحان معاً أو تضحكان معاً.",
    steps: [
      "اقرآ التحدّي معاً",
      "اضغطا «مستعدّان» لبدء المؤقّت",
      "عند انتهاء الوقت قرّرا: أنجزناه أم نتخطّاه",
    ],
    minutes: 7,
    rounds: [],
    fixedRounds: 5,
    depth: "light",
    moods: ["challenge", "laugh"],
    requiresTools: true,
    requiresMovement: true,
    devices: 1,
    hue: "#E8663D",
    category: "laugh",
  },
  {
    id: "G25",
    slug: "what-shall-we-do",
    name: "عجلة الونس",
    tagline: "حين لا تعرفان ماذا تفعلان",
    why: "أربعون نشاطاً مرتّباً حسب المكان والتكلفة والوقت. أديرا العجلة واتركا القرار للحظّ.",
    steps: ["حدّدا المكان والتكلفة والوقت", "أديرا العجلة", "خيار آخر؟ أديراها مرة أخرى"],
    minutes: 5,
    rounds: [],
    fixedRounds: 1,
    depth: "light",
    moods: ["activity"],
    requiresTools: true,
    requiresMovement: true,
    devices: 1,
    hue: "#3B82F6",
    category: "outings",
  },
  {
    id: "G05",
    slug: "finish-the-sentence",
    name: "أكمل الجملة",
    tagline: "بداية جملة، وأنت تكملها بصوتك",
    why: "أحياناً يعجز السؤال المفتوح عن إخراج الكلام. بداية جملة صغيرة تفتح الباب، وشريكك يعيد ما فهمه فتتأكّدان أنكما تسمعان بعضكما.",
    steps: [
      "أكمل الجملة بصوت عالٍ قبل انتهاء الوقت",
      "ليعد شريكك ما فهمه بكلماته",
      "بدّلا الأدوار؛ ثلاث جمل لكلٍّ منكما",
    ],
    minutes: 8,
    rounds: [],
    fixedRounds: 6,
    depth: "mixed",
    moods: ["talk"],
    requiresTools: false,
    requiresMovement: false,
    devices: 1,
    hue: "#8B5CF6",
    category: "talk",
  },
  {
    id: "G06",
    slug: "memory-lane",
    name: "درب الذكريات",
    tagline: "خمس بطاقات تعيدكما إلى أيامكما",
    why: "بدل الأسئلة العامة، أسئلة عن أيامكما أنتما: البدايات، السفر، البيت، والمواقف الطريفة. ولا أحد يصحّح رواية الآخر.",
    steps: [
      "اختارا الباقات التي تحبّانها",
      "استرجعا الذكرى معاً بصوت عالٍ",
      "احفظا عنواناً للذكرى إن أردتما",
    ],
    minutes: 15,
    rounds: [],
    fixedRounds: 5,
    depth: "deep",
    moods: ["talk"],
    requiresTools: false,
    requiresMovement: false,
    devices: 1,
    hue: "#A855F7",
    category: "talk",
  },
  {
    id: "G07",
    slug: "two-truths-and-a-fiction",
    name: "حقيقتان وخيال",
    tagline: "ثلاث جمل عن نفسك، واحدة منها مختلقة",
    why: "قصص صغيرة عن كلٍّ منكما تظهر من بين السطور. ست جولات، ثلاث لكلٍّ منكما، ونقطة لكل تخمين صحيح.",
    steps: [
      "اكتب ثلاث جمل عن نفسك وحدّد المختلقة سراً",
      "مرّر الهاتف ليخمّن شريكك",
      "اكشفا الإجابة وتبادلا الأدوار",
    ],
    minutes: 10,
    rounds: [],
    fixedRounds: 6,
    depth: "light",
    moods: ["talk", "laugh"],
    requiresTools: false,
    requiresMovement: false,
    devices: 1,
    hue: "#6D28D9",
    category: "talk",
  },
  {
    id: "G08",
    slug: "our-world-if",
    name: "عالمنا لو…",
    tagline: "ابنيا عالماً صغيراً بثلاثة قرارات",
    why: "فرضية واحدة وثلاثة أسئلة عنها، تبنيان جوابها معاً. لا إجابة صحيحة، فقط عالم صغير يشبهكما.",
    steps: [
      "اقرآ الفرضية معاً",
      "اقترحا فكرة لكل سؤال ثم اضغطا «اتفقنا»",
      "ثلاث فرضيات وتنتهي الجلسة",
    ],
    minutes: 12,
    rounds: [],
    fixedRounds: 3,
    depth: "light",
    moods: ["talk", "laugh"],
    requiresTools: false,
    requiresMovement: false,
    devices: 1,
    hue: "#9333EA",
    category: "talk",
  },
  {
    id: "G10",
    slug: "silent-charades",
    name: "تمثيل صامت",
    tagline: "كلمة واحدة، دقيقة واحدة، وبلا كلام",
    why: "ستّ جولات من التمثيل الصامت تكشف كم تفهمان بعضكما بلا كلمة واحدة.",
    steps: [
      "اقرأ الكلمة وحدك ثم أخفها",
      "مثّلها صامتاً قبل أن ينتهي المؤقّت",
      "يسجّل شريكك: صحيح أم نتخطّاها",
    ],
    minutes: 15,
    rounds: [],
    fixedRounds: 6,
    depth: "light",
    moods: ["laugh", "challenge"],
    requiresTools: false,
    requiresMovement: true,
    devices: 1,
    hue: "#F97316",
    category: "laugh",
  },
  {
    id: "G11",
    slug: "explain-without",
    name: "اشرح بدون هذه الكلمات",
    tagline: "كلمة واحدة، وثلاث كلمات ممنوعة",
    why: "اشرح الكلمة بأيّ طريقة إلا الطريقة السهلة. تمرين لطيف على سرعة البديهة واللفّ والدوران.",
    steps: [
      "اقرأ الكلمة والممنوعات وحدك",
      "اشرحها بصوتك دون أن تنطق أيّاً منها",
      "يسجّل شريكك: خمّنها أم نتخطّاها",
    ],
    minutes: 10,
    rounds: [6, 10],
    depth: "light",
    moods: ["laugh", "challenge"],
    requiresTools: false,
    requiresMovement: false,
    devices: 1,
    hue: "#EA580C",
    category: "laugh",
  },
  {
    id: "G12",
    slug: "story-one-word",
    name: "قصة كلمة بكلمة",
    tagline: "بداية من خمس كلمات، والباقي عليكما",
    why: "قصة مضحكة تُكتب بالتناوب، جملة قصيرة في كل دور. لا فائز إلا القصة نفسها حين تكتمل.",
    steps: [
      "اقرآ البداية معاً",
      "أضف كلمة أو جملة قصيرة ثم مرّر الهاتف",
      "بعد عشرين دوراً على الأكثر اعرضا القصة كاملة",
    ],
    minutes: 8,
    rounds: [],
    fixedRounds: 1,
    depth: "light",
    moods: ["laugh"],
    requiresTools: false,
    requiresMovement: false,
    devices: 1,
    hue: "#FB923C",
    category: "laugh",
  },
  {
    id: "G13",
    slug: "unusual-announcer",
    name: "المذيع الغريب",
    tagline: "أعلن عن ملعقة بأسلوب نشرة أخبار",
    why: "منتج عادي وأسلوب غريب وجمهور أغرب، وثلاثون ثانية لتصنع منها إعلاناً. أربع فقرات تكفي لتضحككما.",
    steps: [
      "اقرآ المنتج والأسلوب والجمهور",
      "استبدلا عنصراً واحداً إن أردتما، ثم ابدآ",
      "قدّم إعلانك في ثلاثين ثانية",
    ],
    minutes: 8,
    rounds: [],
    fixedRounds: 4,
    depth: "light",
    moods: ["laugh"],
    requiresTools: false,
    requiresMovement: false,
    devices: 1,
    hue: "#F59E0B",
    category: "laugh",
  },
  {
    id: "G14",
    slug: "preference-auction",
    name: "مزاد التفضيلات",
    tagline: "مئة نجمة لكلٍّ منكما، وخمسة امتيازات على المزاد",
    why: "أيّ امتياز يستحقّ نجومك؟ مزايدة سرّية تكشف أولوياتكما الصغيرة وتضحككما حين تتنافسان على الشيء نفسه.",
    steps: [
      "اقرأ الامتياز وزايد عليه سرّاً من نجومك",
      "مرّر الهاتف ليزايد شريكك",
      "الأعلى يفوز ويدفع، والتعادل يجعل الامتياز مشتركاً",
    ],
    minutes: 12,
    rounds: [],
    fixedRounds: 5,
    depth: "light",
    moods: ["laugh", "talk"],
    requiresTools: false,
    requiresMovement: false,
    devices: 1,
    hue: "#D97706",
    category: "laugh",
  },
  {
    id: "G15",
    slug: "home-treasure-hunt",
    name: "كنز البيت",
    tagline: "خمس محطات في البيت، وأدلة يكتبها أحدكما للآخر",
    why: "مغامرة صغيرة داخل بيتكما: أحدكما يخبّئ الرموز ويكتب الأدلة، والآخر يتتبّعها حتى الكنز. لا تتبّع موقع ولا كاميرا.",
    steps: [
      "اكتب خمسة أدلة واترك رمزاً قصيراً في كل مكان",
      "عايِن المسار ثم اقفله وسلّم الهاتف",
      "يدخل شريكك كل رمز ليظهر الدليل التالي",
    ],
    minutes: 30,
    rounds: [],
    fixedRounds: 5,
    depth: "light",
    moods: ["activity", "challenge"],
    requiresTools: true,
    requiresMovement: true,
    devices: 1,
    hue: "#B45309",
    category: "laugh",
  },
  {
    id: "G16",
    slug: "random-cooking",
    name: "تحدّي الطبخ",
    tagline: "ما في مطبخنا الآن… وطبق نصنعه معاً",
    why: "أدخلا ما لديكما فعلاً وما تستبعدانه، وسنقترح طبقاً بسيطاً مقسوماً بينكما. لا مقارنات ولا وعود صحّية، فقط عشاء وضحكة.",
    steps: [
      "اختارا ما لديكما وما تستبعدانه",
      "اقبلا الاقتراح أو اطلبا غيره",
      "اقسما المهمّتين واطبخا معاً",
    ],
    minutes: 45,
    rounds: [],
    fixedRounds: 1,
    depth: "light",
    moods: ["activity"],
    requiresTools: true,
    requiresMovement: false,
    devices: 1,
    hue: "#EF4444",
    category: "laugh",
  },
  {
    id: "G17",
    slug: "draw-and-guess",
    name: "ارسم وخمّن",
    tagline: "كلمة سرّية، دقيقة واحدة، وأصابع ترسم على الشاشة",
    why: "ست جولات يتبادل فيها كلٌّ منكما دور الرسّام. الرسم الرديء يضحك أكثر، والتخمين الصحيح نقطة لكما معاً.",
    steps: [
      "يقرأ الرسّام الكلمة سرّاً ثم يخفيها",
      "يرسم على الشاشة خلال ستين ثانية والشريك يخمّن بصوت عالٍ",
      "اضغطا «خمّنها» عند الإصابة أو «تخطّي»، ثم تبادلا الأدوار",
    ],
    minutes: 15,
    rounds: [],
    fixedRounds: 6,
    depth: "light",
    moods: ["laugh", "challenge"],
    requiresTools: false,
    requiresMovement: false,
    devices: 1,
    hue: "#0EA5E9",
    category: "think",
  },
  {
    id: "G18",
    slug: "emoji-guessing",
    name: "خمّن الرموز",
    tagline: "ثلاثة رموز، وأربعة احتمالات، وحدس مشترك",
    why: "ألغاز قصيرة من الرموز تُحلّ بالنقاش لا بالسرعة. نقطة لكل لغز تحلّانه قبل عرض الحلّ، والتلميح مجّاني.",
    steps: [
      "انظرا إلى الرموز الثلاثة وناقشا معناها",
      "اختارا أحد الحلول الأربعة وثبّتا",
      "لم تصلا؟ اطلبا تلميحاً أو اعرضا الحلّ",
    ],
    minutes: 8,
    rounds: [5, 10],
    depth: "light",
    moods: ["challenge", "laugh"],
    requiresTools: false,
    requiresMovement: false,
    devices: 1,
    hue: "#06B6D4",
    category: "think",
  },
  {
    id: "G19",
    slug: "shared-escape-room",
    name: "غرفة الهروب",
    tagline: "قصة قصيرة وأربعة أقفال، ولكلٍّ منكما نصف الدليل",
    why: "لا يُفتح أي قفل إلا بجمع ما قرأه كلٌّ منكما على حدة، فالحل يمرّ بالكلام بينكما. تلميح ثم حلّ كامل متاحان دائماً بلا خصم.",
    steps: [
      "اختارا قصة واقرآ مقدّمتها",
      "يقرأ كلٌّ منكما دليله الخاص ثم تتبادلانه بالكلام",
      "اكتبا الجواب لفتح القفل، وهكذا حتى النهاية",
    ],
    minutes: 30,
    rounds: [],
    fixedRounds: 4,
    depth: "light",
    moods: ["challenge", "talk"],
    requiresTools: false,
    requiresMovement: false,
    devices: 1,
    hue: "#0891B2",
    category: "think",
  },
  {
    id: "G20",
    slug: "object-memory",
    name: "ذاكرة الأشياء",
    tagline: "عشر ثوانٍ، ثم اختبار للذاكرة",
    why: "شبكة صغيرة من الأشياء تظهر ثم تختفي، وعليكما تذكّرها. أربع جولات، جولتان لكلٍّ منكما، والتعادل نتيجة جميلة.",
    steps: [
      "اختارا مستوى الصعوبة",
      "احفظا الشبكة خلال عشر ثوانٍ",
      "اختارا ما تذكّرتماه ثم تبادلا الأدوار",
    ],
    minutes: 7,
    rounds: [],
    fixedRounds: 4,
    depth: "light",
    moods: ["challenge"],
    requiresTools: false,
    requiresMovement: false,
    devices: 1,
    hue: "#14B8A6",
    category: "think",
  },
  {
    id: "G21",
    slug: "twenty-questions",
    name: "عشرون سؤالاً",
    tagline: "كلمة سرّية، وعشرون سؤالاً بنعم أو لا",
    why: "أحدكما يخفي كلمة والآخر يقترب منها سؤالاً بعد سؤال. لعبة هادئة تصلح للسيارة وقبل النوم.",
    steps: [
      "اقرأ الكلمة وحدك ثم أخفها",
      "يسأل شريكك أسئلة بنعم أو لا",
      "احسب الأسئلة حتى يخمّنها أو تكتمل العشرون",
    ],
    minutes: 10,
    rounds: [2, 4],
    depth: "light",
    moods: ["challenge", "talk"],
    requiresTools: false,
    requiresMovement: false,
    devices: 1,
    hue: "#0D9488",
    category: "think",
  },
  {
    id: "G22",
    slug: "letter-challenge",
    name: "تحدي الحرف",
    tagline: "حرف واحد، ثلاث فئات، ودقيقة لكلٍّ منكما",
    why: "لعبة الكلمات القديمة بنسخة لاثنين: عشر نقاط للإجابة الفريدة، خمس للمتطابقة، وأنتما الحكمان.",
    steps: [
      "اختارا الحرف والفئات الثلاث",
      "يكتب كلٌّ منكما إجاباته خلال دقيقة ثم يمرّر الهاتف",
      "راجعا الإجابات معاً واحسبا النقاط",
    ],
    minutes: 12,
    rounds: [3, 5],
    depth: "light",
    moods: ["challenge"],
    requiresTools: false,
    requiresMovement: false,
    devices: 1,
    hue: "#2563EB",
    category: "think",
  },
  {
    id: "G23",
    slug: "rank-it-like-me",
    name: "رتّبها مثلي",
    tagline: "رتّب أربعة أشياء، وليتوقّع شريكك ترتيبك",
    why: "هل تعرف ما يفضّله شريكك أكثر؟ نقطة عن كل عنصر في مكانه الصحيح، وتبادُل للأدوار كل جولة.",
    steps: [
      "رتّب العناصر الأربعة سراً وثبّت",
      "مرّر الهاتف ليتوقّع شريكك ترتيبك",
      "قارنا الترتيبين ثم تبادلا الأدوار",
    ],
    minutes: 8,
    rounds: [4, 6],
    depth: "light",
    moods: ["talk", "challenge"],
    requiresTools: false,
    requiresMovement: false,
    devices: 1,
    hue: "#1D4ED8",
    category: "think",
  },
  {
    id: "G24",
    slug: "daily-duo-puzzle",
    name: "لغز اليوم",
    tagline: "لغز واحد كل يوم، يحلّه اثنان",
    why: "لغز قصير يتغيّر مع كل يوم جديد. يقترح كلٌّ منكما حلّاً سراً، ثم تكشفان الجواب وشرحه معاً.",
    steps: ["اقرآ لغز اليوم", "يختار كلٌّ منكما حلّاً سراً ثم يمرّر الهاتف", "اكشفا الجواب واقرآ الشرح"],
    minutes: 4,
    rounds: [],
    fixedRounds: 1,
    depth: "light",
    moods: ["challenge", "talk"],
    requiresTools: false,
    requiresMovement: false,
    devices: 1,
    hue: "#3730A3",
    category: "think",
  },
  {
    id: "G26",
    slug: "our-night-planner",
    name: "مخطّط سهرتنا",
    tagline: "افتتاح، لعبة، وختام لطيف في حدود وقتكما",
    why: "حين يكون الوقت محدوداً والمزاج واضحاً، يقترح المخطّط سهرة من ثلاثة أجزاء يمكن تبديل أيّ جزء منها وحفظ الخطة لاحقاً.",
    steps: [
      "اختارا الوقت المتاح والمزاج",
      "بدّلا أيّ جزء لا يعجبكما",
      "احفظا الخطة أو ابدآ السهرة فوراً",
    ],
    minutes: 3,
    rounds: [],
    fixedRounds: 1,
    depth: "light",
    moods: ["activity"],
    requiresTools: true,
    requiresMovement: false,
    devices: 1,
    hue: "#10B981",
    category: "outings",
  },
  {
    id: "G27",
    slug: "our-wish-jar",
    name: "جرّة أمنياتنا",
    tagline: "أمنيات صغيرة نجمعها، ثم نبدأ بواحدة",
    why: "مكان واحد لكل ما نؤجّله: نزهة قريبة، طبق جديد، أو شروق نراه مرّة. لا تذكيرات ولا مواعيد ملزمة.",
    steps: [
      "أضيفا أمنية وحدّدا صاحبها",
      "اختارا واحدة معاً واكتبا خطوتها الأولى",
      "علّماها «جرّبناها» حين تحدث",
    ],
    minutes: 8,
    rounds: [],
    depth: "light",
    moods: ["activity", "talk"],
    requiresTools: false,
    requiresMovement: false,
    devices: 1,
    hue: "#059669",
    category: "outings",
  },
  {
    id: "G28",
    slug: "our-memory-map",
    name: "خريطة ذكرياتنا",
    tagline: "لحظاتكما بعنوان وتاريخ ومدينة، محفوظة على هذا الجهاز",
    why: "الأماكن تحفظ ما ننساه. اجمعا لحظاتكما المهمّة في خطّ زمنيّ صغير يبقى بينكما وحدكما، وتنبّهكما ذكراه السنوية حين تقترب.",
    steps: [
      "أضيفا ذكرى بعنوان وتاريخ ومدينة",
      "تصفّحاها حسب السنة أو المدينة",
      "احذفا ما لا تريدان بقاءه",
    ],
    minutes: 10,
    rounds: [],
    depth: "deep",
    moods: ["talk"],
    requiresTools: false,
    requiresMovement: false,
    devices: 1,
    hue: "#047857",
    category: "outings",
  },
  {
    id: "G29",
    slug: "letter-to-the-future",
    name: "رسالة إلى المستقبل",
    tagline: "اكتبا رسالة لا تُفتح إلا في يومها",
    why: "بعض الكلام يصل أجمل حين ينتظر. اكتب رسالة تبقى مقفلة حتى تاريخ تختاره، ثم افتحاها معًا يومها.",
    steps: ["اكتب رسالتك واختر من تصل إليه", "راجعا المستلم وتاريخ الفتح", "احفظاها وانتظرا يومها"],
    minutes: 8,
    rounds: [],
    depth: "deep",
    moods: ["talk"],
    requiresTools: false,
    requiresMovement: false,
    devices: 1,
    hue: "#065F46",
    category: "outings",
  },
  {
    id: "G30",
    slug: "first-time-album",
    name: "ألبوم أوّل مرّة",
    tagline: "تجربة جديدة كل مرّة، وانطباع يبقى لكما",
    why: "الأشياء التي نجرّبها لأوّل مرّة تصنع أجمل الذكريات. اختارا تجربة صغيرة آمنة، جرّباها، ثم دوّنا انطباعكما في سجلّ خاصّ لا يُنشر.",
    steps: ["اختارا اقتراحًا أو اطلبا واحدًا عشوائيًا", "جرّباه معًا", "اكتبا انطباعكما واحفظاه"],
    minutes: 10,
    rounds: [],
    depth: "light",
    moods: ["activity"],
    requiresTools: false,
    requiresMovement: false,
    devices: 1,
    hue: "#34D399",
    category: "outings",
  },
  {
    id: "G31",
    slug: "gratitude-card",
    name: "بطاقة امتنان",
    tagline: "كلمتان لطيفتان تختمان بهما اليوم",
    why: "بطاقة واحدة لكلٍّ منكما تختمان بها الجلسة بكلام محدّد وطيّب. لا نقاط ولا حفظ؛ ما يُقال يبقى بينكما.",
    steps: ["اقرأ البداية وأكملها بكلماتك", "مرّر البطاقة إلى شريكك", "بطاقة أخرى أو أنهيا الجلسة"],
    minutes: 4,
    rounds: [],
    fixedRounds: 2,
    depth: "deep",
    moods: ["talk"],
    requiresTools: false,
    requiresMovement: false,
    devices: 1,
    hue: "#EC4899",
    category: "useful",
  },
  {
    id: "G32",
    slug: "weekly-team-mission",
    name: "مهمّتنا الأسبوعية",
    tagline: "إنجاز صغير واحد، بخطوتين بيننا",
    why: "مهمّة واحدة في الأسبوع تُقسم خطوتين، ولكما أن تؤجّلاها متى شئتما. التقدّم مشترك؛ لا لوحة متابعة لأحدكما على الآخر.",
    steps: [
      "اختارا مهمّة أو اكتبا واحدة",
      "عدّلا الخطوتين ومَن يفعل أيّهما",
      "علّما كل خطوة عند إنجازها",
    ],
    minutes: 5,
    rounds: [],
    fixedRounds: 1,
    depth: "light",
    moods: ["activity"],
    requiresTools: false,
    requiresMovement: true,
    devices: 1,
    hue: "#DB2777",
    category: "useful",
  },
  {
    id: "G33",
    slug: "learn-together",
    name: "نتعلّم معاً",
    tagline: "مهارة صغيرة في درس قصير وتمرين وسؤال واحد",
    why: "تعلّم شيء جديد معاً أجمل من تعلّمه وحدك: كلمات بلغة أخرى، عقدة حبل، أو صورة أفضل بالهاتف. بلا شهادات ولا درجات.",
    steps: [
      "اختارا درساً واقرآه معاً",
      "نفّذا التمرين ثم اضغطا «أنجزناه»",
      "أجيبا عن سؤال المراجعة واقرآ الشرح",
    ],
    minutes: 15,
    rounds: [],
    fixedRounds: 1,
    depth: "light",
    moods: ["activity", "challenge"],
    requiresTools: true,
    requiresMovement: true,
    devices: 1,
    hue: "#BE185D",
    category: "useful",
  },
  {
    id: "G34",
    slug: "creative-photo-challenge",
    name: "تحدّي الصورة",
    tagline: "موضوعان، صورتان، وضحكة عند العرض",
    why: "يسحب كلٌّ منكما موضوعاً ويصوّره بتطبيق الكاميرا لديه. لا نطلب إذن الكاميرا ولا نرفع أي صورة، والأطرف تختارانها معاً.",
    steps: [
      "اسحبا موضوعين: واحد لكلٍّ منكما",
      "صوّرا خارج التطبيق، بمؤقّت أو بدونه",
      "اعرضا الصورتين واختارا الأطرف معاً",
    ],
    minutes: 20,
    rounds: [],
    fixedRounds: 3,
    depth: "light",
    moods: ["activity", "laugh"],
    requiresTools: false,
    requiresMovement: true,
    devices: 1,
    hue: "#F472B6",
    category: "useful",
  },
  {
    id: "G35",
    slug: "religious-quiz",
    name: "مسابقة معرفة دينية",
    tagline: "خمسة أسئلة بالتناوب، ومع كل إجابة شرح ومصدر",
    why: "معلومات من السيرة وسور القرآن والأخلاق، متّفق عليها ومصدرها مذكور. النقاط للمتعة داخل اللعبة فقط.",
    steps: [
      "اختارا المواضيع",
      "أجيبا بالتناوب عن خمسة أسئلة",
      "اقرآ الإجابة والشرح والمصدر بعد كل سؤال",
    ],
    minutes: 8,
    rounds: [],
    fixedRounds: 5,
    depth: "light",
    moods: ["challenge"],
    requiresTools: false,
    requiresMovement: false,
    devices: 1,
    hue: "#64748B",
    category: "faith",
    gated: "religious",
  },
  {
    id: "G36",
    slug: "good-deed-together",
    name: "عمل خير معاً",
    tagline: "فكرة صغيرة نافعة، تختارانها بحرّية",
    why: "ثلاثون فكرة بسيطة تنفع أهلكما أو جيرانكما، مع وقتها وأدواتها. اقبلا ما يناسبكما، والتخطّي بلا أي عتب.",
    steps: [
      "فعّلا «بدون تكلفة» إن أردتما",
      "اقرآ الفكرة ومدّتها وأدواتها",
      "اقبلاها أو اطلبا فكرة أخرى",
    ],
    minutes: 15,
    rounds: [],
    fixedRounds: 1,
    depth: "light",
    moods: ["activity"],
    requiresTools: true,
    requiresMovement: false,
    devices: 1,
    hue: "#475569",
    category: "faith",
  },
] as const;

export const gameBySlug = (slug: string) => GAMES.find((g) => g.slug === slug);
export const gameById = (id: string) => GAMES.find((g) => g.id === id);

export const MOOD_LABEL: Record<Mood, string> = {
  talk: "نتكلّم",
  laugh: "نضحك",
  challenge: "نتحدّى",
  activity: "نختار نشاطاً",
};

export const CATEGORY_LABEL: Record<Category, string> = {
  talk: "حديث وتعارف",
  laugh: "ضحك وحركة",
  think: "تفكير وتعاون",
  outings: "خروجات وذكريات",
  useful: "أنشطة مفيدة",
  faith: "أنشطة دينية وخيرية (اختياري)",
};
